allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js-pure: false
  esbuild: true
  unrs-resolver: true
overrides:
  test-exclude: 8.0.0
  jsdom: 28.0.0
  'chrome-launcher@^0.13.4': 1.2.1
  lighthouse: 13.4.1
  qs: 6.16.0
  tmp: 0.2.7
  'uuid@^8.3.1': 11.1.1
minimumReleaseAgeExclude:
  - '@tiptap/core@3.30.3 || 3.30.6'
  - '@tiptap/extension-blockquote@3.30.3 || 3.30.6'
  - '@tiptap/extension-bold@3.30.3 || 3.30.6'
  - '@tiptap/extension-bubble-menu@3.30.3 || 3.30.6'
  - '@tiptap/extension-bullet-list@3.30.3 || 3.30.6'
  - '@tiptap/extension-code-block-lowlight@3.30.3 || 3.30.6'
  - '@tiptap/extension-code-block@3.30.3 || 3.30.6'
  - '@tiptap/extension-code@3.30.3 || 3.30.6'
  - '@tiptap/extension-document@3.30.3 || 3.30.6'
  - '@tiptap/extension-dropcursor@3.30.3 || 3.30.6'
  - '@tiptap/extension-floating-menu@3.30.3 || 3.30.6'
  - '@tiptap/extension-gapcursor@3.30.3 || 3.30.6'
  - '@tiptap/extension-hard-break@3.30.3 || 3.30.6'
  - '@tiptap/extension-heading@3.30.3 || 3.30.6'
  - '@tiptap/extension-horizontal-rule@3.30.3 || 3.30.6'
  - '@tiptap/extension-image@3.30.3 || 3.30.6'
  - '@tiptap/extension-italic@3.30.3 || 3.30.6'
  - '@tiptap/extension-link@3.30.3 || 3.30.6'
  - '@tiptap/extension-list-item@3.30.3 || 3.30.6'
  - '@tiptap/extension-list-keymap@3.30.3 || 3.30.6'
  - '@tiptap/extension-list@3.30.3 || 3.30.6'
  - '@tiptap/extension-ordered-list@3.30.3 || 3.30.6'
  - '@tiptap/extension-paragraph@3.30.3 || 3.30.6'
  - '@tiptap/extension-strike@3.30.3 || 3.30.6'
  - '@tiptap/extension-text@3.30.3 || 3.30.6'
  - '@tiptap/extension-underline@3.30.3 || 3.30.6'
  - '@tiptap/extensions@3.30.3 || 3.30.6'
  - '@tiptap/pm@3.30.3 || 3.30.6'
  - '@tiptap/react@3.30.3 || 3.30.6'
  - '@tiptap/starter-kit@3.30.3 || 3.30.6'
  - '@types/react-dom@19.2.5'
  - '@typescript-eslint/parser@8.69.0'
  - '@typescript-eslint/project-service@8.69.0'
  - '@typescript-eslint/scope-manager@8.69.0'
  - '@typescript-eslint/tsconfig-utils@8.69.0'
  - '@typescript-eslint/types@8.69.0'
  - '@typescript-eslint/typescript-estree@8.69.0'
  - '@typescript-eslint/visitor-keys@8.69.0'
